GET http://localhost:8000/flights
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOnsiX2lkIjoiNjAwNzkyYjAzYzJiNjU2MzU0NzM2MGE0IiwidXNlck5hbWUiOiJTaHJpcCIsImVtYWlsIjoiZGFuc2hhd210QGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiJTaGF3MTEwNSJ9LCJpYXQiOjE2MTExMTMwMzl9.rx1TG-YPyH9XtIS0lDDmi89M-z0qijJ2py6NxVxUbcM
###

POST http://localhost:8000/flights
Content-Type: application/json

{
    "name": "Malta to Mitiga",
    "desc": "11:00 - 12:00",
    "stops": "5",
    "depLoc": "MIA",
    "arrLoc": "BEN",
    "depTime": "12/01/21 9:00",
    "edt": "12/01/21 9:00",
    "eta": "12/01/21 12:00"
}

###

DELETE http://localhost:8000/flights/60037794c85a573e50e0e8f4

###
PATCH http://localhost:8000/flights/60037794c85a573e50e0e8f4
Content-Type: application/json

{
    "name": ""
}

###

POST http://localhost:8000/flights/signup
Content-Type: application/json

{
    "userName": "DanielShaw",
    "email": "danshawmt@hotmail.com",
    "password": "Shaw1104"
}

###

POST http://localhost:8000/flights/login
Content-Type: application/json

{
    "userName": "Shrip",
    "password":"Shaw1105"
}

###

POST http://localhost:8000/flights/login
Content-Type: application/json

{
    "userName": "DanielShaw",
    "password": "Shaw1104"
}