GET http://localhost:8000/flights

###

POST http://localhost:8000/flights
Content-Type: application/json

{
    "name": "Malta to Mitiga",
    "desc": "11:00 - 12:00",
    "latitude": 56.7,
    "longitude": 51.2
}

###

DELETE http://localhost:8000/flights/60037794c85a573e50e0e8f4

###
PATCH http://localhost:8000/flights/60037794c85a573e50e0e8f4
Content-Type: application/json

{
    "name": ""
}