GET http://localhost:8000/flights/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOnsiX2lkIjoiNjAwODE0NjliMGFjZmY0YWQ0NmU1OWYwIiwidXNlck5hbWUiOiJTaHJpcCIsImVtYWlsIjoiaG9mQGdtYWlsLmNvbiIsInBhc3N3b3JkIjoiTG1hbyIsImF1dGhMdmwiOjAsIl9fdiI6MH0sImlhdCI6MTYxMTE1MTg5M30.cRNskv5Jwcm9-WuLnH20eTClPJI3OU0qaJFJlF8O-zM

###

POST http://localhost:8000/flights
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOnsiX2lkIjoiNjAwOGMwYjQzZmYyODY1NzYwNGRjMzI2IiwidXNlck5hbWUiOiJTaHJpcCIsImVtYWlsIjoiaG9mQGdtYWlsLmNvbiIsInBhc3N3b3JkIjoiTG1hbyIsImF1dGhMdmwiOjQsIl9fdiI6MH0sImlhdCI6MTYxMTE4NjQ1NX0.Ggw_isiRTNO7rA3_dzHGR19I1_Hm75xL5iw9Cup8E-4
Content-Type: application/json

{
    "name": "Malta to lmao",
    "desc": "11:00 - 12:00",
    "stops": "5",
    "depLoc": "MIA",
    "arrLoc": "BENINA",
    "depTime": "12/01/21 9:00",
    "edt": "12/01/21 9:00",
    "eta": "12/01/21 12:00"
}

###

DELETE http://localhost:8000/flights/60037794c85a573e50e0e8f4

###
PATCH http://localhost:8000/flights/60037794c85a573e50e0e8f4
Content-Type: application/json

{
    "name": ""
}

###

POST http://localhost:8000/flights/signup
Content-Type: application/json

{
    "userName": "Shripa",
    "email": "hof@gmail.con",
    "password": "Lmao"
}

###

POST http://localhost:8000/flights/login
Content-Type: application/json

{
    "userName": "Shrip",
    "password":"Lmao"
}

###

POST http://localhost:8000/flights/login
Content-Type: application/json

{
    "userName": "Shrip",
    "password": "Lmao"
}